-- SMAJ Ecosystem Supabase Auth admin + application policies
-- Run this in Supabase Dashboard -> SQL Editor.
--
-- IMPORTANT:
-- - Public form submissions write to public.application.
-- - Admin dashboard reads/updates require Supabase Auth + public.admin_users.
-- - Do not use or expose a service_role key in website code.

-- 1. Admin allowlist table.
create table if not exists public.admin_users (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null unique references auth.users(id) on delete cascade,
    email text not null unique,
    full_name text,
    role text not null default 'admin' check (role in ('owner', 'admin', 'reviewer')),
    created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- 2. Audit log table.
create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    application_id text not null,
    admin_user_id uuid references public.admin_users(id) on delete set null,
    admin_auth_user_id uuid references auth.users(id) on delete set null,
    action text not null,
    old_status text,
    new_status text,
    notes text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.audit_logs enable row level security;

-- 3. Admin helper function for RLS.
create or replace function public.is_smaj_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.admin_users
        where user_id = auth.uid()
    );
$$;

grant execute on function public.is_smaj_admin() to authenticated;

-- 4. Application table RLS.
-- IMPORTANT: the table name is public.application (singular).
alter table public.application enable row level security;

drop policy if exists "Allow public application inserts" on public.application;
drop policy if exists "Allow authenticated admins to read application" on public.application;
drop policy if exists "Allow authenticated admins to update application" on public.application;

create policy "Allow public application inserts"
on public.application
for insert
to anon
with check (status = 'pending');

create policy "Allow authenticated admins to read application"
on public.application
for select
to authenticated
using (public.is_smaj_admin());

create policy "Allow authenticated admins to update application"
on public.application
for update
to authenticated
using (public.is_smaj_admin())
with check (
    public.is_smaj_admin()
    and status in ('pending', 'interview', 'accepted', 'rejected')
);

-- Secure applicant status lookup by application ID + edit token.
-- This avoids broad anon SELECT on public.application.
create or replace function public.get_application_status(
    p_application_id text,
    p_edit_token text
)
returns table (
    application_id text,
    application_type text,
    status text,
    edit_link text,
    data jsonb,
    files jsonb,
    created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
    select
        a.application_id,
        a.application_type,
        a.status,
        a.edit_link,
        a.data::jsonb,
        a.files::jsonb,
        a.created_at
    from public.application a
    where a.application_id = p_application_id
      and a.edit_token = p_edit_token
    limit 1;
$$;

grant execute on function public.get_application_status(text, text) to anon, authenticated;

-- 5. Admin users RLS.
drop policy if exists "Admins can read admin users" on public.admin_users;

create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (
    user_id = auth.uid()
    or public.is_smaj_admin()
);

-- 6. Audit logs RLS.
drop policy if exists "Admins can read audit logs" on public.audit_logs;
drop policy if exists "Admins can insert audit logs" on public.audit_logs;

create policy "Admins can read audit logs"
on public.audit_logs
for select
to authenticated
using (public.is_smaj_admin());

create policy "Admins can insert audit logs"
on public.audit_logs
for insert
to authenticated
with check (public.is_smaj_admin());

-- 7. Storage policy for public application file uploads.
-- Keep the bucket name as "applicatoins" because that is the bucket name currently used by the site.
drop policy if exists "Allow public application file uploads" on storage.objects;

create policy "Allow public application file uploads"
on storage.objects
for insert
to anon
with check (bucket_id = 'applicatoins');

-- 8. After creating an admin in Supabase Auth, allowlist them:
--
-- insert into public.admin_users (user_id, email, full_name, role)
-- values (
--   'AUTH_USER_UUID_HERE',
--   'admin@smaj.org',
--   'SMAJ Admin',
--   'owner'
-- );
